[package]
name = "puizcloud"
version = "0.1.0"
authors = ["Victor Nivet <victor@saumon.ninja>"]
edition = "2018"
license = "MIT/Apache-2.0"

[dependencies]
actix-web = "0.7.16"
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"
# clap = "2.32"